1) alpha=xTY

In [11]:
import numpy as np
def dot_product_vector_column(vector, column):
    """Compute the dot product of a vector and a column."""
    return np.dot(vector, column)
vector1= np.array([1,2,3])
vector1_transpose=np.transpose(vector1)
column = np.array([[4], [5], [6]])

result = dot_product_vector_column(vector1_transpose, column)
print(result)

#flop count


[32]


In [6]:
#flop count
def flop_count(dim):
    return 2*dim
dim = len(vector1)
flop_count = flop_count(dim)
print(flop_count)

6


2) saxpy

In [7]:
import numpy as np

def saxpy(alpha, vector_x, vector_y):
    """Compute the SAXPY operation: alpha * vector_x + vector_y."""
    return alpha * vector_x + vector_y

def flop_count_saxpy(dim):
    """Calculate the floating-point operations (flops) for a SAXPY operation
    with vectors of dimension `dim`."""
    return 2 * dim  # Flop count for SAXPY operation

# Example usage:
alpha = 2.0
vector_x = np.array([1, 2, 3])
vector_y = np.array([4, 5, 6])

result = saxpy(alpha, vector_x, vector_y)
print("Result of SAXPY operation:", result)

# Calculate flop count for SAXPY operation
dim = len(vector_x)
flop_count = flop_count_saxpy(dim)
print("Flop count for SAXPY operation:", flop_count)


Result of SAXPY operation: [ 6.  9. 12.]
Flop count for SAXPY operation: 6


3) gaxpy

In [9]:
import numpy as np

def gaxpy(alpha, vector_x, vector_y):
    """Compute the GAXPY operation: alpha * vector_x + vector_y."""
    return alpha * vector_x + vector_y

def flop_count_gaxpy(dim):
    """Calculate the floating-point operations (flops) for a GAXPY operation
    with vectors of dimension `dim`."""
    return 2 * dim  # Flop count for GAXPY operation

# Example usage:
alpha = 2.0
vector_x = np.array([1, 2, 3])
vector_y = np.array([4, 5, 6])

result = gaxpy(alpha, vector_x, vector_y)
print("Result of GAXPY operation:", result)

# Calculate flop count for GAXPY operation
dim = len(vector_x)
flop_count = flop_count_gaxpy(dim)
print("Flop count for GAXPY operation:", flop_count)


Result of GAXPY operation: [ 6.  9. 12.]
Flop count for GAXPY operation: 6


In [ ]:
import numpy as np

def outer_product(vector_x, vector_y):
    """Compute the outer product of two vectors."""
    return np.outer(vector_x, vector_y)


In [12]:
import numpy as np

def add_matrix_outer_product(matrix_a, vector_u, vector_v):
    """Add a matrix A with the outer product of vectors u and v."""
    outer_product_uv = np.outer(vector_u, vector_v)
    return matrix_a + outer_product_uv

def flop_count_add_matrix_outer_product(n, m):
    """Calculate the floating-point operations (flops) for adding a matrix with
    the outer product of vectors of dimensions nx1 and mx1."""
    return n * m  # Flop count for adding a matrix with the outer product

n, m = 3, 4  # Dimensions of the matrix
matrix_a = np.random.random((n, m))
vector_u = np.random.random((n, 1))
vector_v = np.random.random((m, 1))
vector_v_transpose=np.transpose(vector_v)

result = add_matrix_outer_product(matrix_a, vector_u, vector_v_transpose)
print("Result of adding matrix A with the outer product of vectors u and v:")
print(result)

# Calculate flop count for adding matrix with outer product
flop_count = flop_count_add_matrix_outer_product(n, m)
print("Flop count for adding matrix with outer product:", flop_count)


Result of adding matrix A with the outer product of vectors u and v:
[[0.0752852  0.95606624 0.10739347 0.19238578]
 [0.54439102 0.40632201 0.74575894 0.1540397 ]
 [0.26036908 0.73872797 1.01313921 0.63235061]]
Flop count for adding matrix with outer product: 12


In [1]:
import numpy as np

def add_matrix_outer_product(matrix_a, vector_u, vector_v):
    """Add a matrix A with the outer product of vectors u and v."""
    outer_product_uv = np.dot(vector_u, vector_v)
    return matrix_a + outer_product_uv

def flop_count_add_matrix_outer_product(n, m, r):
    """Calculate the floating-point operations (flops) for adding a matrix with
    the outer product of vectors of dimensions nxr and rxm."""
    return 2 * n * m * r  # Flop count for adding a matrix with the outer product

# Example usage:
n, m, r = 3, 4, 2  # Dimensions of the matrix and vectors
matrix_a = np.random.random((n, m))
vector_u = np.random.random((n, r))
vector_v = np.random.random((r, m))

result = add_matrix_outer_product(matrix_a, vector_u, vector_v)
print("Result of adding matrix A with the outer product of vectors u and v:")
print(result)

# Calculate flop count for adding matrix with outer product
flop_count = flop_count_add_matrix_outer_product(n, m, r)
print("Flop count for adding matrix with outer product:", flop_count)


Result of adding matrix A with the outer product of vectors u and v:
[[0.63468111 0.70592813 1.10274206 0.99535798]
 [1.227124   1.2652945  1.00206297 0.80182799]
 [0.50693869 1.217705   0.867422   1.18225052]]
Flop count for adding matrix with outer product: 48


In [14]:
import numpy as np
def count_flop_Case5(A,B,C,D):
    n=np.shape(A)[0]
    m=np.shape(A)[1]
    s=np.shape(B)[1]
    r=np.shape(B)[1]
    temp=np.zeros((n,m))
    flop=0
    for i in range(n):
        for j in range(m):
            for k in range(r):
                for l in range(s):
                     temp[i,j]=B[i,l]*C[l,k]*D[k,j]
                     flop=flop+2
                A[i,j]=A[i,j]+temp[i,j]
                flop=flop+1
    return A,flop 

In [15]:
n=20
m=12
s=12
r=12 
A=np.random.random((n,m))
B=np.random.random((n,r))
C=np.random.random((r,s))
D=np.random.random((s,m))
a_new,flop=count_flop_Case5(A,B,C,D)

In [16]:
print(flop)

72000


In [13]:
print(n*m*(2*r+2*s-1))

11280
