In [5]:
import numpy as np

def read_matrix_from_file(file_path, rows, cols):
    try:
        # Read the file and convert data to a 1D array
        with open(file_path, 'r') as file:
            data = [float(line.strip()) for line in file]

        
        matrix = np.array(data).reshape(rows, cols)

        return matrix

    except Exception as e:
        print(f"Error reading matrix from file: {e}")
        return None

# Example usage:
file_path = 'matrix_data.txt'  # Replace with your file path
num_rows = 3
num_cols = 4

result_matrix = read_matrix_from_file(file_path, num_rows, num_cols)

if result_matrix is not None:
    print("Matrix read from file:")
    print(result_matrix)


Error reading matrix from file: could not convert string to float: ''


In [8]:
def read_matrix_from_file(filename):
    
    import numpy as np
    
    matrix = []
    
    with open(filename, 'r') as file:
        
        for line in file:
            
            row = list(map(int, line.strip().split()))
            matrix.append(row)
            
    matrix=np.array(matrix)
    
    return matrix

B = read_matrix_from_file('matrixA.txt')
print(B)

[[1]
 [2]
 [3]
 [4]]


In [7]:
A=np.array([[2,3],[1,-1]])
print(A)


[[ 2  3]
 [ 1 -1]]


In [9]:
def matrix_multiply(A, B):
    
    # Check conformability
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrices are not conformable for multiplication.")

    # Perform matrix-matrix multiplication
    C = np.dot(A, B)

    return C

A = np.array([[1,2,3],[0,3,-1]])
B = np.array([[1,2],[0,-2],[1,0]])

C = matrix_multiply(A, B)

print("AB:")
print(C)

D = matrix_multiply(B, A)

print("BA:")
print(D)

AB:
[[ 4 -2]
 [-1 -6]]
BA:
[[ 1  8  1]
 [ 0 -6  2]
 [ 1  2  3]]


In [10]:
import numpy as np

def convert_to_upper_triangular(matrix, vector):
    # Combine the coefficient matrix and the right-hand side vector
    augmented_matrix = np.column_stack((matrix, vector))

    rows, cols = augmented_matrix.shape

    for pivot_row in range(min(rows, cols - 1)):
        # Find the pivot element
        pivot_element = augmented_matrix[pivot_row, pivot_row]

        if pivot_element == 0:
            # If the pivot element is zero, swap with a row below to avoid division by zero
            nonzero_row = np.argmax(augmented_matrix[pivot_row + 1:, pivot_row]) + pivot_row + 1
            augmented_matrix[[pivot_row, nonzero_row]] = augmented_matrix[[nonzero_row, pivot_row]]
            pivot_element = augmented_matrix[pivot_row, pivot_row]

        # Scale the current row to make the pivot element 1
        augmented_matrix[pivot_row, :] /= pivot_element

        # Eliminate lower triangular elements in the column
        for row in range(pivot_row + 1, rows):
            factor = augmented_matrix[row, pivot_row]
            augmented_matrix[row, :] -= factor * augmented_matrix[pivot_row, :]

    return augmented_matrix[:, :-1], augmented_matrix[:, -1]

# Example usage:
coeff_matrix = np.array([[2, -1, 3], [4, 2, -1], [3, 5, -2]], dtype=float)
rhs_vector = np.array([9, 8, 3], dtype=float)

upper_triangular_matrix, new_rhs_vector = convert_to_upper_triangular(coeff_matrix, rhs_vector)

print("Upper Triangular Matrix:")
print(upper_triangular_matrix)
print("\nUpdated Right-Hand Side Vector:")
print(new_rhs_vector)


Upper Triangular Matrix:
[[ 1.   -0.5   1.5 ]
 [ 0.    1.   -1.75]
 [ 0.    0.    1.  ]]

Updated Right-Hand Side Vector:
[ 4.5        -2.5         1.17948718]
